# Generated by Django 3.0.8 on 2020-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20200804_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(null=True, upload_to='deploy/videos/%Y/%m/%d/'),
        ),
    ]
